= Analiza modeli językowych

== Metodologia

Wybrany dokument, wraz z definicjami wszystkich dwudziestu pięciu technik, przekazano w ramach pojedynczego polecenia (ang. _prompt_) czterem publicznie dostępnym modelom językowym: GPT-5.6 Luna (dostępny w ChatGPT) @openai2026chatgpt, Gemini 3.6 Flash @google2026gemini, DeepSeek R1 @deepseek2026r1 oraz Kimi K2.6 w trybie Instant @moonshot2026kimi. Każdy z modeli otrzymał identyczne instrukcje. Zadanie polegało na jednoczesnej ocenie wszystkich osiemnastu akapitów i wygenerowaniu spójnej odpowiedzi, w której każda decyzja klasyfikacyjna miała zostać uzasadniona w jednym lub dwóch zdaniach. Osadzenie pełnych definicji technik w treści polecenia częściowo nawiązuje do metodologii Jose i Greenstadt @jose2025llms, którzy w ramach zadania BSNLP 2025 zastosowali analogiczny zabieg w bardziej rozbudowanej formie - lecz tylko w drugim z dwóch podzadań konkursu, klasyfikacji konkretnych etykiet: osobno dla każdego akapitu, w dwóch przebiegach obejmujących połowę tagsetu naraz, z wymuszonym łańcuchem rozumowania i progiem pewności 0,99 przy ekstrakcji fragmentów, naprzemiennie na modelach gpt-4o-mini i o4-mini. W pierwszym podzadaniu konkursu - samej detekcji obecności techniki, bliższej pierwszemu pytaniu z anotacji w niniejszej pracy - użyły natomiast wyłącznie modelu o4-mini, bez łańcucha rozumowania i bez podziału na przebiegi, co według ich własnych ustaleń ograniczyło uzyskiwany recall. Wszystkie cztery modele użyte w niniejszej pracy natywnie wspierają tryb rozumowania (ang. _thinking_/_reasoning_) i z niego korzystały przy generowaniu odpowiedzi, mimo że polecenie nie narzucało im tego wprost. Zastosowane tu podejście - jeden prompt obejmujący cały dokument naraz, bez podziału na przebiegi, progu pewności ani wymuszonej struktury łańcucha rozumowania - pozostaje więc uproszczeniem drugiego podzadania metody Jose i Greenstadt przede wszystkim pod względem inżynierii promptu, a nie faktycznego zaangażowania modeli w rozumowanie nad tekstem. Nawiązuje ono również do wcześniejszych, niepublikowanych badań własnych, w których skuteczność modeli językowych weryfikowano na korpusie anglojęzycznym, jednak bez wykorzystania ustrukturyzowanej taksonomii @kostecki2025mozliwosci.

== Porównanie wyników z anotacją referencyjną

#table(
  columns: (1.3fr, 1.3fr, 1.2fr),
  align: (left, center, center),
  stroke: 0.5pt,
  inset: 6pt,
  table.header(
    [*Model*],
    [*Zgodność z anotacją*],
    [*Rozbieżności*],
  ),
  [ChatGPT], [16/18 (89%)], [2],
  [Gemini], [15/18 (83%)], [3],
  [DeepSeek], [15/18 (83%)], [3],
  [Kimi], [16/18 (89%)], [2],
)

Zgodność klasyfikacji modeli z anotacją referencyjną wyniosła od 83% do 89% - przy czym chodzi tu o zgodność, nie o poprawność: pojedyncza anotacja ręczna, jak zaznaczono we wnioskach, nie pretenduje do roli obiektywnego wzorca. Co istotne, w żadnym przypadku żaden model nie ocenił jako neutralnego akapitu, który anotator uznał za zawierający technikę perswazyjną. Wszystkie rozbieżności miały odwrotny kierunek: modele wskazywały technikę tam, gdzie anotator jej nie widział, zawsze w tych samych trzech akapitach (P04, P15, P17) - żaden model nie pomylił się poza tym zbiorem. Można to tłumaczyć na dwa sposoby - albo jako skłonność modeli do nadrozpoznawania perswazji w treściach czysto informacyjnych, albo jako możliwość, że pojedynczy anotator przeoczył subtelniejsze użycie technik akurat w tych fragmentach; rozstrzygnięcie między tymi wyjaśnieniami wymagałoby drugiego anotatora. Warto również zauważyć, że modele wykazywały wyższą zgodność wewnętrzną (między sobą) niż z anotacją referencyjną: dla szesnastu z osiemnastu akapitów wygenerowano identyczny werdykt u wszystkich czterech badanych systemów. Nie stoi to w sprzeczności z różną liczbą rozbieżności poszczególnych modeli w tabeli powyżej - z tych szesnastu jednomyślnych akapitów piętnaście to klasyfikacje zgodne z anotacją referencyjną, a jeden (P04) to rozbieżność, co do której wszystkie cztery modele są zgodne między sobą. Pozostałe dwa akapity, P15 i P17, to jedyne miejsca, w których modele nie są zgodne nawet między sobą (na każdym z nich trzy modele wskazują technikę, a jeden nie) - stąd różnice w łącznej liczbie rozbieżności poszczególnych modeli.

Znaczne rozbieżności względem anotacji referencyjnej zaobserwowano na poziomie przypisywania konkretnych etykiet. Systemy znacznie częściej sięgały po etykietę _Loaded Language_ - wskazywano ją w niemal każdym akapicie uznanym za perswazyjny, podczas gdy w anotacji referencyjnej przypisano ją zaledwie w połowie przypadków. Zjawisko to jest wyraźnie widoczne na przykładzie akapitu P02, w którym mówczyni przytacza historię kobiety po odmowie wykonania legalnej aborcji przez szpital. W anotacji referencyjnej wskazano tu odwołanie do wartości, odwołanie do strachu oraz odwołanie do czasu (uzasadnione tym, że opowieść pada bezpośrednio po wzmiance o wcześniejszym przesunięciu debaty przez marszałka Sejmu, co nadaje jej wydźwięk pilności); wszystkie cztery modele niezależnie od siebie przypisały mu wspólną parę etykiet - odwołanie do litości (_Appeal to Pity_) oraz manipulacyjne słownictwo (_Loaded Language_), przy czym dwa z czterech modeli dodały do tej pary jeszcze trzecią etykietę (odpowiednio odwołanie do strachu i podważanie wiarygodności) - a żaden z nich nie wskazał odwołania do czasu. Modele zgodziły się więc ze sobą nawzajem bardziej niż z anotacją referencyjną, co sugeruje wspólne obciążenie w stronę technik łatwo rozpoznawalnych leksykalnie kosztem tych, które - jak zauważa Grice w kontekście implikatur konwersacyjnych - wymagają wykroczenia poza dosłowną treść zdania i uwzględnienia szerszego kontekstu wypowiedzi.