= Podsumowanie

Przeprowadzone w rozdziale pierwszym zestawienie taksonomii BSNLP z klasycznymi kategoriami logiki nieformalnej w dużej mierze potwierdziło początkowe założenia, większość technik uwzględnionych w BSNLP ma swoje bezpośrednie odpowiedniki wśród znanych błędów we wnioskowaniu (takich jak _ad hominem_ czy odwołanie do autorytetu). Z kolei anotacja manualna, opisana w rozdziale drugim, wykazała, że w analizowanym materiale dominowało słownictwo manipulacyjne, atak na reputację oraz uzasadnienie, podczas gdy odwrócenie uwagi wystąpiło w umiarkowanym stopniu, wyłącznie za sprawą nowo dodanej w 2025 roku techniki odwołania do litości, a uproszczenie i wezwanie do działania należały do najrzadszych kategorii.

Porównanie anotacji referencyjnej z klasyfikacją przeprowadzoną przez cztery modele językowe, przedstawione w rozdziale trzecim, ujawniło wyraźny wzorzec: żaden z badanych systemów nie pominął akapitu ocenionego przez anotatora jako perswazyjny, za to wszystkie wykazały skłonność do wskazywania technik w akapitach uznanych za neutralne i czysto informacyjne oraz do nadmiarowego stosowania etykiety _Loaded Language_. Bliższe spojrzenie na te trzy akapity sugeruje, że rozbieżność nie jest przypadkowa: P04 to skonwencjonalizowana formuła grzecznościowa, P15 to głównie dane liczbowe, a P17 to relacja z debaty w innym kraju. We wszystkich trzech obecny jest pozytywny lub kontrastowy ton językowy, ale nie towarzyszy mu żadna perswazyjna funkcja w argumentacji samej mówczyni. Anotator uchwycił to, kierując się funkcją wypowiedzi w kontekście całości, modele zaś zareagowały na powierzchniowe cechy językowe. Nie wyklucza to całkowicie omyłki anotatora, ale pokazuje, że rozbieżność da się przynajmniej częściowo wyjaśnić bez zakładania błędu po którejkolwiek ze stron, typowy scenariusz tzw. pętli feedbacku, w której rozbieżności między anotatorem a systemem służą do doprecyzowania definicji kategorii i przykładów wzorcowych, a nie tylko do arbitrażu przez kolejnego anotatora.

Niniejsze badanie ma istotne ograniczenia metodologiczne. Analizie poddano wyłącznie jeden dokument i wystąpienie pojedynczej osoby, co nie pozwala na uogólnienie wniosków na całość polskiego dyskursu parlamentarnego. Anotacji referencyjnej dokonał samodzielnie autor pracy: to nie tylko kwestia braku drugiego, niezależnego anotatora, ale też ryzyka nieświadomego obciążenia własnymi oczekiwaniami badawczymi, którego nie da się wykluczyć przy samoanotacji. Jak wskazują sami twórcy taksonomii BSNLP, zgodność ocen między profesjonalnymi, niezależnymi anotatorami w tego typu zadaniach jest stosunkowo niska (α ≈ 0,34) @piskorski2023semeval; innymi słowy, inny anotator pracujący nad tym samym tekstem mógłby części akapitów przypisać inne etykiety, nie popełniając przy tym błędu. Przyjęte w tej pracy etykiety należy więc traktować jako jedną z kilku możliwych, obronionych klasyfikacji, a nie jako jedyny poprawny wzorzec.

Ograniczenia dotyczą też strony eksperymentu z modelami językowymi. Testowanie miało charakter jednorazowy i nie uwzględniało weryfikacji powtarzalności odpowiedzi przy ponownym przetwarzaniu tego samego tekstu. Względem drugiego podzadania metody Jose i Greenstadt @jose2025llms, które posłużyło za wzór, było to podejście uproszczone przede wszystkim pod względem inżynierii promptu: bez wymuszonego progu pewności przy wskazywaniu technik i bez podziału promptu na przebiegi obejmujące mniejsze podzbiory tagsetu. Wszystkie cztery testowane modele natywnie wspierają jednak tryb myślenia i korzystały z niego przy generowaniu odpowiedzi, mimo że prompt tego nie wymuszał. Skłonności do nadrozpoznawania technik i faworyzowania etykiety _Loaded Language_, opisanej w rozdziale trzecim, nie da się więc łatwo wytłumaczyć brakiem namysłu ze strony modeli - warto ją zbadać dalej właśnie dlatego, że pojawiła się mimo rozumowania nad tekstem, nie z jego braku.

Naturalnym kierunkiem dalszych prac badawczych byłoby zatem powtórzenie zaprezentowanej procedury na obszerniejszym korpusie dokumentów, z uwzględnieniem niezależnej weryfikacji przez drugiego anotatora w celu wyznaczenia miary zgodności. Wskazane byłoby również sprawdzenie, czy zaobserwowana tendencja modeli do nadużywania etykiety _Loaded Language_ utrzymuje się w przypadku zastosowania alternatywnych wariantów formułowania poleceń (ang. _prompt engineering_), a także czy powtarza się przy użyciu najpotężniejszych, flagowych wariantów tych samych rodzin modeli (np. GPT-5.6 Sol, Gemini 3.1 Pro, Claude Opus 5 czy Kimi K3) zamiast ich szybszych, darmowo dostępnych odmian zastosowanych w niniejszym eksperymencie.